---
- block:
  - name: setup time zone
    file:
      src: "/usr/share/zoneinfo/{{ sys_config_timezone }}"
      dest: /etc/localtime
      state: link

  - name: generate /etc/adjtime
    command: hwclock --systohc
    args:
      creates: /etc/adjtime

  - name: get /etc/adjtime
    command: cat /etc/adjtime
    changed_when: false
    register: adjtime

  - name: set hardware clock to utc
    command: hwclock --systohc --utc
    when: adjtime.stdout.find('UTC') == -1
  tags: time-zone

- block:
  # Ensure locale-gen is used on host
  - name: stat locale.gen
    stat: path=/etc/locale.gen
    register: file

  - name: generate locales
    locale_gen: name={{ item }}
    with_items: "{{ sys_config_locale }}"
    when: file.stat.exists

  - name: setup locale & keymap
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
    with_items: "{{ sys_config_locale_files }}"
  tags: locale

- block:
  - name: set hostname
    hostname: name={{ sys_config_hostname | mandatory }}

  # Systems using systemd require fallback for chroot
  rescue:
  - name: fallback - set hostname persistent
    template:
      src: hostname.j2
      dest: /etc/hostname

  - name: fallback - set hostname runtime
    command: hostname -F /etc/hostname
    when: ansible_hostname != sys_config_hostname
  tags: hostname
